#!/bin/bash

LIST_OF_DEVICES=$(adb devices | grep -v "List" | grep -v "adb I " | grep -v "* daemon" | cut -f 1)

for SERIAL in $LIST_OF_DEVICES; do
  adb -s $SERIAL $@ &
done

for job in `jobs -p`; do
  wait $job
done
